### ISSUE TITLE
Screen shader parser: Screen shader parse failed

### ISSUE THREAD

**Issue by vitezprchal** [loqusion/hyprshade#39]
When using the main branch of Hyprshade, shaders fail to parse correctly.

### Steps to Reproduce

1. Check out the main branch of the Hyprland repository.
2. Attempt to run Hyprland with custom shaders (blue filters).

**Comment by loqusion** [comment]
Please provide your configuration file (`hyprshade.toml`), the command(s) you ran (e.g. `hyprshade on blue-light-filter`), and the command output.

**Comment by loqusion** [comment]
Actually, did you set `decoration:screen_shader` to the path to [`blue-light-filter.glsl.mustache`](https://github.com/loqusion/hyprshade/blob/main/shaders/blue-light-filter.glsl.mustache) manually?

**Comment by vitezprchal** [comment]
I managed to fix it by copying https://github.com/loqusion/hyprshade/tree/3.2.1/shaders into my shaders directory instead of using shaders from master branch. I used the default example config that is provided in code.

**Comment by loqusion** [comment]
The [shaders](https://github.com/loqusion/hyprshade/tree/main/shaders) on the `main` branch are actually [Mustache](https://mustache.github.io/) templates, so they will only work when rendered into GLSL. Hyprshade on the `main` branch does this with `hyprshade on`, `hyprshade toggle`, etc. so that shaders are configurable (see the [`4.0.0` README](https://github.com/loqusion/hyprshade/tree/docs/readme-4.0.0) for more info).

Did you activate the shader with Hyprshade on the `main` branch, with Hyprshade pre-`4.0.0`, or some other way?

**Comment by vitezprchal** [comment]
At first I copied config from the master branch and activated the shaders using `hyprshade on blue-light-filter`. It didn't produce any relevant output, only displaying 'parse failed.' Eventually, I managed to fix it using the method I described earlier here.

**Comment by loqusion** [comment]
Was the `hyprshade` executable from the `main` branch or was it a stable version? If `main`, this could be a bug.

**Comment by vitezprchal** [comment]
It was a stable version, it was my mistake because of copying shaders from `main` branch.

**Comment by loqusion** [comment]
Shaders should not need manual installation, they are [included in the wheel](https://github.com/loqusion/hyprshade/blob/da37264298ea47f4ba10a76b76b5b60fb9e8244b/pyproject.toml#L62-L63). Did your installation of Hyprshade not include them?

**Comment by vitezprchal** [comment]
Since I'm using nixos, I didn't declare shaders path in my config. Instead, I manually placed it in my .config directory from github repo.
