### ISSUE TITLE
Error with hyprshade auto

### ISSUE THREAD

**Issue by arthsmn** [loqusion/hyprshade#41]
When I try to use `hyprshade auto` it gives me this error: `Error: '<=' not supported between instances of 'str' and 'datetime.time'`.

**Comment by HarshNarayanJha** [comment]
Can you share your `hyprshade.toml`? Maybe you have a wrong setting on the start or end time

**Comment by loqusion** [comment]
It sounds like you included quotes around the value for `start_time` or `end_time` in your Hyprshade config (like `start_time = "07:32:00"`), which caused it to be deserialized as a string (`str`) instead of `time`. See the [TOML spec "Local Time" section](https://toml.io/en/v1.0.0#local-time) for how time should be formatted.

Better error reporting should be coming eventually.

**Comment by HarshNarayanJha** [comment]
Exactly!

**Comment by HarshNarayanJha** [comment]
Hey @loqusion if you are busy with other things (you are!) then I might create some issue templates requiring to include `hyprshade.toml` file and other critical info.

**Comment by loqusion** [comment]
@HarshNarayanJha That would be great! Feel free to make a PR any time.

**Comment by arthsmn** [comment]
Sorry for the missing config file! This was exactly the problem. I was using NixOS to write toml config from nix but it seems not to support this part of the config yet, or idk how to do it, thanks!
